"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { KeyRound, Power, Save, Settings2, UserCog, UserPlus, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { api, type User } from "@/features/settings/services/api";

type Config = { roles: { value: string; label: string }[]; capabilities: { by_role: Record<string, string[]> }; user: User };
type UsersPage = { results: User[] };
const capabilityLabel = (capability: string) => capability.replaceAll("_", " ");

export function SettingsScreen() {
  const [config, setConfig] = useState<Config | null>(null); const [me, setMe] = useState<User | null>(null); const [team, setTeam] = useState<User[]>([]);
  const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const [configuration, current] = await Promise.all([api<Config>("config/"), api<User>("users/me/")]); setConfig(configuration); setMe(current); if (current.role === "admin" || current.is_staff || current.is_superuser) { const users = await api<UsersPage>("users/?page_size=100"); setTeam(users.results); } } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo cargar la configuración."); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function updateProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!me) return; setSaving(true); const fields = new FormData(event.currentTarget); try { const updated = await api<User>("users/me/", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(fields)) }); setMe(updated); setNotice("Perfil actualizado."); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo actualizar el perfil."); } finally { setSaving(false); } }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fields = Object.fromEntries(new FormData(event.currentTarget)); setSaving(true); try { await api("users/me/password/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(fields) }); event.currentTarget.reset(); setNotice("Contraseña actualizada. Te recomendamos volver a iniciar sesión."); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo cambiar la contraseña."); } finally { setSaving(false); } }
  async function updatePreferences(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api("users/me/preferences/", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, rows_per_page: Number(values.rows_per_page) }) }); setNotice("Preferencias guardadas."); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudieron guardar las preferencias."); } }
  async function createUser(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api("users/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); event.currentTarget.reset(); setNotice("Cuenta creada."); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo crear la cuenta."); } }
  async function updateRole(user: User, role: string) { try { await api(`users/${user.id}/`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role }) }); setNotice("Rol actualizado."); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo actualizar el rol."); } }
  async function deactivate(user: User) { if (!confirm(`¿${user.is_active ? "Dar de baja" : "Reactivar"} a ${user.full_name || user.username}?`)) return; try { await api(`users/${user.id}/`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ is_active: !user.is_active }) }); setNotice("Estado de la cuenta actualizado."); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo actualizar la cuenta."); } }
  const admin = Boolean(me && (me.role === "admin" || me.is_staff || me.is_superuser));
  return <section className="space-y-6"><header><h1 className="font-[family-name:var(--font-poppins)] text-3xl font-semibold">Configuración</h1><p className="mt-1 text-sm text-[#5E5E66]">Gestiona tu perfil, preferencias y el acceso del equipo.</p></header>{notice && <p className="rounded-lg border border-[#D8D8DC] bg-white p-3 text-sm">{notice}</p>}
    <div className="grid gap-6 xl:grid-cols-2"><Card className="border-[#D8D8DC]"><CardContent className="p-6"><div className="mb-5 flex items-center gap-2"><UserCog className="size-5 text-[#8941E8]"/><div><h2 className="font-semibold">Mi perfil</h2><p className="text-sm text-[#5E5E66]">Datos usados en tu cuenta.</p></div></div>{me && <form className="grid gap-4 sm:grid-cols-2" onSubmit={updateProfile}><Field name="first_name" label="Nombre" defaultValue={me.first_name}/><Field name="last_name" label="Apellido" defaultValue={me.last_name}/><Field name="username" label="Usuario" defaultValue={me.username}/><Field name="phone" label="Teléfono" defaultValue={me.phone}/><div className="sm:col-span-2"><Field name="email" label="Correo de inicio de sesión" type="email" defaultValue={me.email}/></div><div className="sm:col-span-2"><Button disabled={saving} type="submit"><Save/>Guardar cambios</Button></div></form>}</CardContent></Card>
      <Card className="border-[#D8D8DC]"><CardContent className="p-6"><div className="mb-5 flex items-center gap-2"><KeyRound className="size-5 text-[#8941E8]"/><div><h2 className="font-semibold">Seguridad</h2><p className="text-sm text-[#5E5E66]">Actualiza tu contraseña.</p></div></div><form className="space-y-4" onSubmit={changePassword}><Field name="current_password" label="Contraseña actual" type="password" required/><Field name="new_password" label="Nueva contraseña" type="password" required/><Field name="new_password_confirm" label="Confirmar nueva contraseña" type="password" required/><Button disabled={saving} type="submit"><KeyRound/>Cambiar contraseña</Button></form></CardContent></Card></div>
    {me && <Card className="border-[#D8D8DC]"><CardContent className="p-6"><h2 className="font-semibold">Preferencias de interfaz</h2><p className="mt-1 text-sm text-[#5E5E66]">Se guardan únicamente en tu perfil.</p><form className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end" onSubmit={updatePreferences}><label className="grid gap-1.5 text-sm font-medium">Tema<select name="theme" defaultValue={String(me.preferences.theme ?? "system")} className="h-10 rounded-md border border-[#D8D8DC] bg-white px-3"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label className="grid gap-1.5 text-sm font-medium">Filas por página<Input name="rows_per_page" type="number" min="10" max="200" defaultValue={String(me.preferences.rows_per_page ?? 25)}/></label><Button type="submit" variant="outline"><Save/>Guardar preferencias</Button></form></CardContent></Card>}
    {config && <Card className="border-[#D8D8DC]"><CardContent className="p-6"><div className="mb-4 flex items-center gap-2"><Settings2 className="size-5 text-[#8941E8]"/><div><h2 className="font-semibold">Roles y capacidades</h2><p className="text-sm text-[#5E5E66]">Permisos definidos por la plataforma.</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{config.roles.map((role) => <div key={role.value} className="rounded-lg bg-[#F7F7F8] p-4"><p className="font-medium">{role.label}</p><div className="mt-3 flex flex-wrap gap-1">{(config.capabilities.by_role[role.value] ?? []).map((capability) => <Badge key={capability} variant="outline" className="capitalize">{capabilityLabel(capability)}</Badge>)}</div></div>)}</div></CardContent></Card>}
    {admin && <Card className="border-[#D8D8DC]"><CardContent className="p-6"><div className="mb-5 flex items-center gap-2"><Users className="size-5 text-[#8941E8]"/><div><h2 className="font-semibold">Equipo</h2><p className="text-sm text-[#5E5E66]">Crea cuentas, asigna roles o da de baja accesos.</p></div></div><form className="mb-6 grid gap-3 rounded-lg bg-[#F7F7F8] p-4 sm:grid-cols-2 lg:grid-cols-5" onSubmit={createUser}><Field name="first_name" label="Nombre" required/><Field name="last_name" label="Apellido" required/><Field name="email" label="Correo" type="email" required/><Field name="password" label="Contraseña inicial" type="password" required/><label className="grid gap-1.5 text-sm font-medium">Rol<select name="role" className="h-10 rounded-md border border-[#D8D8DC] bg-white px-3">{config?.roles.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select></label><Button className="lg:col-span-5 lg:w-fit" type="submit"><UserPlus/>Crear cuenta</Button></form><div className="space-y-3">{team.map((user) => <div className="flex flex-col gap-3 rounded-lg border border-[#D8D8DC] p-3 sm:flex-row sm:items-center" key={user.id}><div className="min-w-0 flex-1"><p className="font-medium">{user.full_name || user.username}</p><p className="truncate text-sm text-[#5E5E66]">{user.email}</p></div><Badge variant={user.is_active ? "outline" : "destructive"}>{user.is_active ? "Activo" : "Inactivo"}</Badge><select aria-label={`Rol de ${user.full_name || user.username}`} className="h-9 rounded-md border border-[#D8D8DC] bg-white px-2 text-sm" value={user.role ?? ""} onChange={(e) => void updateRole(user, e.target.value)}><option value="" disabled>Sin rol asignado</option>{config?.roles.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select><Button title={user.is_active ? "Dar de baja" : "Reactivar"} size="icon-sm" variant="ghost" disabled={user.id === me?.id} onClick={() => void deactivate(user)}><Power className={user.is_active ? "text-[#D64545]" : "text-[#8941E8]"}/></Button></div>)}</div></CardContent></Card>}
  </section>;
}
function Field({ label, ...props }: React.ComponentProps<typeof Input> & { label: string }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<Input {...props}/></label>; }
