"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowUpRight, BarChart3, BookOpen, BriefcaseBusiness, CheckCircle2, CircleAlert, Clock3, FileText, MessageSquare, RefreshCw, UserRound, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { api } from "@/features/settings/services/api";
import { cn } from "@/lib/utils";

type Summary = { contacts: Count; conversations: Count & { open: number; closed: number; to_start: number; unanswered: number }; messages: Count; cases: Count & { open: number; won: number; overdue: number; unassigned: number }; proposals: Count & { sent: number; total_sent_cop: number }; knowledge: { documents: number; indexed: number; pending: number; chunks: number } };
type Count = { total: number; new?: number; change_pct?: number | null };
type Funnel = { total_cases: number; won: number; lost: number; win_rate_pct: number | null; average_days_to_close: number | null; stages: { status: string; label: string; total: number; pct_of_total: number }[] };
type Series = { series: { date: string; total: number; inbound?: number; outbound?: number }[]; total: number };
type PendingItem = { contact?: string; status?: string; contact_id?: number; case_id?: number; requirement_id?: number; title?: string; priority?: string; error?: string };
type Pending = Record<string, { total: number; items: PendingItem[]; days?: number }>;
type Activity = { results: { id: number; case_id: number; contact: string; label: string; actor: string | null; created_at: string }[] };
type Agents = { results: { user_id: number; email: string; role: string; cases_open: number; cases_closed: number; cases_won: number; messages_sent: number }[] };

const pendingLabels: Record<string, string> = { conversations_waiting_reply: "Conversaciones esperando respuesta", cases_overdue: "Casos vencidos", cases_stale: "Casos sin movimiento", cases_unassigned: "Casos sin asesor", proposals_followup: "Propuestas para seguimiento", requirements_in_review: "Requerimientos en revisión", knowledge_documents_pending: "Documentos sin indexar" };
const formatMoney = (value: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(value || 0);
const formatDate = (value: string) => new Intl.DateTimeFormat("es-CO", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export function DashboardScreen() {
  const [days, setDays] = useState("30"); const [summary, setSummary] = useState<Summary | null>(null); const [funnel, setFunnel] = useState<Funnel | null>(null); const [series, setSeries] = useState<Series | null>(null); const [pending, setPending] = useState<Pending | null>(null); const [activity, setActivity] = useState<Activity | null>(null); const [agents, setAgents] = useState<Agents | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = `?days=${days}`; const [summaryData, funnelData, seriesData, pendingData, activityData, agentsData] = await Promise.all([api<Summary>(`dashboard/summary/${query}`), api<Funnel>(`dashboard/funnel/${query}`), api<Series>(`dashboard/timeseries/?metric=conversations&days=${days}`), api<Pending>("dashboard/pending/?limit=4"), api<Activity>("dashboard/activity/?limit=6"), api<Agents>(`dashboard/agents/${query}`), api(`dashboard/conversations/${query}`), api(`dashboard/contacts/${query}`)]); setSummary(summaryData); setFunnel(funnelData); setSeries(seriesData); setPending(pendingData); setActivity(activityData); setAgents(agentsData); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar el dashboard."); } finally { setLoading(false); } }, [days]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const max = Math.max(...(series?.series.map((point) => point.total) ?? [1]), 1);
  const cards = summary ? [{ label: "Contactos nuevos", value: summary.contacts.new ?? summary.contacts.total, change: summary.contacts.change_pct, icon: Users, href: "/clientes", color: "bg-[#FFF4BC] text-[#735900]" }, { label: "Conversaciones abiertas", value: summary.conversations.open, suffix: `${summary.conversations.unanswered} sin responder`, icon: MessageSquare, href: "/conversaciones?state=open", color: "bg-[#E9DAFF] text-[#6A22BD]" }, { label: "Casos abiertos", value: summary.cases.open, suffix: `${summary.cases.overdue} vencidos`, icon: BriefcaseBusiness, href: "/clientes", color: "bg-[#D8F3EA] text-[#166E54]" }, { label: "Propuestas enviadas", value: summary.proposals.sent, suffix: formatMoney(summary.proposals.total_sent_cop), icon: FileText, href: "/propuestas", color: "bg-[#DDEBFF] text-[#205FBD]" }] : [];
  return <section className="space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-[#8941E8]">Vista general</p><h1 className="font-[family-name:var(--font-poppins)] text-3xl font-semibold">Buenos días</h1><p className="mt-1 text-sm text-[#5E5E66]">El pulso comercial y operativo de Psicotips.</p></div><div className="flex gap-2"><select aria-label="Periodo del dashboard" value={days} onChange={(event) => setDays(event.target.value)} className="h-9 rounded-lg border border-[#D8D8DC] bg-white px-3 text-sm"><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="365">Último año</option></select><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={cn("size-4", loading && "animate-spin")}/>Actualizar</Button></div></header>
    {error && <div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><CircleAlert className="size-5 shrink-0"/>{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => { const Icon = card.icon; return <Link key={card.label} href={card.href}><Card className="h-full border-[#D8D8DC] transition-transform hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-4"><div className="flex items-start justify-between"><div><p className="text-sm text-[#5E5E66]">{card.label}</p><p className="mt-2 font-[family-name:var(--font-poppins)] text-3xl font-semibold">{loading ? "—" : card.value}</p></div><span className={cn("flex size-10 items-center justify-center rounded-xl", card.color)}><Icon className="size-5"/></span></div><p className="mt-3 text-xs text-[#5E5E66]">{card.change != null ? `${card.change > 0 ? "+" : ""}${card.change}% vs. periodo anterior` : card.suffix ?? "Sin comparación previa"}</p></CardContent></Card></Link>; })}</div>
    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card className="border-[#D8D8DC]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Conversaciones creadas</h2><p className="mt-1 text-sm text-[#5E5E66]">Actividad diaria del periodo seleccionado.</p></div><BarChart3 className="size-5 text-[#8941E8]"/></div><div className="mt-7 flex h-44 items-end gap-1.5">{series?.series.map((point) => <div className="group flex h-full min-w-0 flex-1 items-end" key={point.date}><div title={`${point.date}: ${point.total}`} className="w-full rounded-t-sm bg-[#8941E8] transition-colors group-hover:bg-[#F8CB00]" style={{ height: `${point.total ? Math.max((point.total / max) * 100, 5) : 2}%` }}/></div>)}</div><div className="mt-2 flex justify-between text-xs text-[#5E5E66]"><span>{series?.series[0]?.date ?? ""}</span><span>{series?.total ?? 0} conversaciones</span><span>{series?.series.at(-1)?.date ?? ""}</span></div></CardContent></Card>
      <Card className="border-[#D8D8DC]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Salud del conocimiento</h2><p className="mt-1 text-sm text-[#5E5E66]">Base usada por la IA.</p></div><BookOpen className="size-5 text-[#8941E8]"/></div><div className="mt-6 grid grid-cols-2 gap-3"><Metric label="Documentos" value={summary?.knowledge.documents}/><Metric label="Indexados" value={summary?.knowledge.indexed}/><Metric label="Pendientes" value={summary?.knowledge.pending} alert/><Metric label="Chunks" value={summary?.knowledge.chunks}/></div><Link href="/conocimiento" className="mt-5 flex items-center gap-1 text-sm font-medium text-[#6A22BD] hover:underline">Gestionar conocimiento <ArrowUpRight className="size-4"/></Link></CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Card className="border-[#D8D8DC]"><CardContent className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Embudo comercial</h2><p className="mt-1 text-sm text-[#5E5E66]">{funnel?.total_cases ?? 0} casos · {funnel?.win_rate_pct == null ? "Sin cierres aún" : `${funnel.win_rate_pct}% tasa de cierre`}</p></div><Badge variant="outline">{funnel?.won ?? 0} ganados</Badge></div><div className="mt-5 space-y-3">{funnel?.stages.map((stage) => <div key={stage.status}><div className="mb-1 flex justify-between text-sm"><span>{stage.label}</span><span className="font-medium">{stage.total}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#EFEFF1]"><div className="h-full rounded-full bg-[#8941E8]" style={{ width: `${stage.pct_of_total}%` }}/></div></div>)}</div></CardContent></Card>
      <Card className="border-[#D8D8DC]"><CardContent className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Última actividad</h2><p className="mt-1 text-sm text-[#5E5E66]">Movimientos recientes del proceso.</p></div><Clock3 className="size-5 text-[#8941E8]"/></div><div className="mt-4 space-y-4">{activity?.results.length ? activity.results.map((item) => <div className="flex gap-3" key={item.id}><span className="mt-1.5 size-2 shrink-0 rounded-full bg-[#F8CB00]"/><div className="min-w-0"><p className="text-sm font-medium">{item.label}</p><p className="truncate text-xs text-[#5E5E66]">{item.contact} · {item.actor ?? "Sistema"} · {formatDate(item.created_at)}</p></div></div>) : <p className="py-5 text-center text-sm text-[#5E5E66]">No hay actividad reciente.</p>}</div></CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Card className="border-[#D8D8DC]"><CardContent className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Para atender hoy</h2><p className="mt-1 text-sm text-[#5E5E66]">Elementos que requieren una acción.</p></div><CheckCircle2 className="size-5 text-[#8941E8]"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{pending && Object.entries(pending).map(([key, group]) => <PendingCard key={key} label={pendingLabels[key] ?? key} group={group} kind={key}/>)}</div></CardContent></Card>
      <Card className="border-[#D8D8DC]"><CardContent className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Carga por asesor</h2><p className="mt-1 text-sm text-[#5E5E66]">Actividad del periodo.</p></div><UserRound className="size-5 text-[#8941E8]"/></div><div className="mt-4 space-y-3">{agents?.results.length ? agents.results.map((agent) => <div className="flex items-center gap-3" key={agent.user_id}><span className="flex size-8 items-center justify-center rounded-full bg-[#E9DAFF] text-xs font-semibold text-[#6A22BD]">{agent.email.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{agent.email}</p><p className="text-xs text-[#5E5E66]">{agent.cases_open} abiertos · {agent.messages_sent} mensajes</p></div><Badge variant="outline">{agent.role}</Badge></div>) : <p className="py-5 text-center text-sm text-[#5E5E66]">No hay actividad de asesores.</p>}</div></CardContent></Card></div>
  </section>;
}
function Metric({ label, value, alert }: { label: string; value?: number; alert?: boolean }) { return <div className="rounded-lg bg-[#F7F7F8] p-3"><p className="text-xs text-[#5E5E66]">{label}</p><p className={cn("mt-1 text-xl font-semibold", alert && value ? "text-amber-700" : "")}>{value ?? "—"}</p></div>; }
function PendingCard({ label, group, kind }: { label: string; group: { total: number; items?: PendingItem[] }; kind: string }) { const href = kind === "knowledge_documents_pending" ? "/conocimiento" : kind === "conversations_waiting_reply" ? "/conversaciones?state=open&unanswered=true" : "/clientes"; const item = group.items?.[0]; return <Link href={href} className="rounded-lg border border-[#E5E5E8] p-3 transition-colors hover:bg-[#F7F7F8]"><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{label}</p><Badge variant={group.total ? "destructive" : "outline"}>{group.total}</Badge></div>{item && <p className="mt-2 truncate text-xs text-[#5E5E66]">{item.contact ?? item.title ?? "Sin detalle"}{item.status ? ` · ${item.status}` : ""}</p>}</Link>; }
