"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3, Bell, BookOpen, FileText, Menu, MessageSquare, Radio, Settings, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import { PsicotipsChat } from "@/components/psicotips-chat";

const navigation = [{ label: "Dashboard", href: "/dashboard", icon: BarChart3 }, { label: "Clientes", href: "/clientes", icon: Users }, { label: "Conversaciones", href: "/conversaciones", icon: MessageSquare }, { label: "Canales", href: "/channels", icon: Radio }, { label: "Conocimiento", href: "/conocimiento", icon: BookOpen }, { label: "Propuestas", href: "/propuestas", icon: FileText, disabled: true }, { label: "Configuración", href: "/configuracion", icon: Settings }];
function Nav({ onNavigate }: { onNavigate?: () => void }) { const pathname = usePathname(); return <nav className="space-y-1" aria-label="Navegación principal">{navigation.map((item) => { const Icon = item.icon; const active = pathname.startsWith(item.href); if (item.disabled) return <span aria-disabled="true" title="Próximamente" className="flex min-h-10 cursor-not-allowed items-center gap-3 rounded-lg px-3 text-sm font-medium text-white/35" key={item.href}><Icon className="size-4" />{item.label}<span className="ml-auto text-[10px]">Próximamente</span></span>; return <Link onClick={onNavigate} className={cn("flex min-h-10 items-center gap-3 rounded-lg px-3 text-sm font-medium transition-colors", active ? "bg-[#F8CB00] text-[#1E1E21]" : "text-white/75 hover:bg-white/10 hover:text-white")} href={item.href} key={item.href}><Icon className="size-4" />{item.label}</Link>; })}</nav> }
export function AdminShell({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-[#F7F7F8]"><aside className="fixed inset-y-0 left-0 hidden w-64 bg-[#1E1E21] p-5 md:block"><Link href="/dashboard" className="mb-9 block font-[family-name:var(--font-poppins)] text-xl font-bold text-white">Psico<span className="text-[#F8CB00]">Tips</span></Link><Nav /><p className="absolute bottom-6 text-xs text-white/45">Administración</p></aside><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-[#D8D8DC] bg-white px-4 md:ml-64 md:px-8"><Sheet><SheetTrigger render={<Button variant="ghost" size="icon" aria-label="Abrir navegación" className="md:hidden" />}><Menu /></SheetTrigger><SheetContent side="left" className="w-72 bg-[#1E1E21] p-5 text-white"><Link href="/dashboard" className="mb-9 block font-[family-name:var(--font-poppins)] text-xl font-bold">Psico<span className="text-[#F8CB00]">Tips</span></Link><Nav /></SheetContent></Sheet><div className="ml-auto flex items-center gap-3"><Button variant="ghost" size="icon" aria-label="Notificaciones"><Bell /></Button><span title="Gestiona tu perfil desde Configuración" aria-label="Perfil gestionado desde Configuración" className="flex size-9 cursor-not-allowed items-center justify-center rounded-full bg-[#8941E8]/45 text-sm font-semibold text-white">AD</span></div></header><main className="p-4 md:ml-64 md:p-8">{children}</main><PsicotipsChat /></div> }
