"use client";

import { FormEvent, Fragment, useEffect, useRef, useState } from "react";
import { Bot, Loader2, MessageCircle, Send, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type Message = { role: "user" | "assistant"; content: string };
const welcome: Message = { role: "assistant", content: "Hola, soy el asistente de Psicotips. ¿En qué puedo ayudarte?" };

export function PsicotipsChat() {
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState<Message[]>([welcome]); const [text, setText] = useState(""); const [sending, setSending] = useState(false);
  const sessionId = useRef(""); const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { let id = sessionStorage.getItem("psicotips-chat-session"); if (!id) { id = `panel-${crypto.randomUUID()}`; sessionStorage.setItem("psicotips-chat-session", id); } sessionId.current = id; }, []);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, sending]);
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const content = text.trim(); if (!content || sending || !sessionId.current) return; setText(""); setMessages((previous) => [...previous, { role: "user", content }]); setSending(true); try { const response = await fetch("/api/chat/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chatInput: content, sessionId: sessionId.current }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.message || "No se pudo obtener respuesta."); setMessages((previous) => [...previous, { role: "assistant", content: result.output }]); } catch (error) { setMessages((previous) => [...previous, { role: "assistant", content: error instanceof Error ? error.message : "Ocurrió un error al contactar al asistente." }]); } finally { setSending(false); } }
  return <div className="fixed right-4 bottom-4 z-40 sm:right-6 sm:bottom-6">{open && <section aria-label="Chat con Psicotips" className="mb-3 flex h-[min(42rem,calc(100vh-7rem))] w-[calc(100vw-2rem)] max-w-2xl flex-col overflow-hidden rounded-2xl border border-[#D8D8DC] bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#1E1E21] p-4 text-white"><div className="flex items-center gap-2"><span className="flex size-8 items-center justify-center rounded-full bg-[#F8CB00] text-[#1E1E21]"><Bot className="size-4"/></span><div><p className="text-sm font-semibold">Asistente Psicotips</p><p className="text-xs text-white/65">Base de conocimiento</p></div></div><Button aria-label="Cerrar chat" variant="ghost" size="icon-sm" className="text-white hover:bg-white/10 hover:text-white" onClick={() => setOpen(false)}><X/></Button></header><div className="flex-1 space-y-3 overflow-y-auto bg-[#F7F7F8] p-5">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={cn("max-w-[92%] rounded-2xl px-4 py-3 text-sm leading-relaxed", message.role === "user" ? "ml-auto rounded-br-md bg-[#8941E8] text-white" : "rounded-bl-md bg-white text-[#1E1E21] shadow-sm")}><MarkdownMessage content={message.content}/></div>)}{sending && <div className="flex w-fit items-center gap-2 rounded-2xl rounded-bl-md bg-white px-3 py-2 text-sm shadow-sm"><Loader2 className="size-4 animate-spin text-[#8941E8]"/>Escribiendo…</div>}<div ref={bottom}/></div><form onSubmit={send} className="flex gap-2 border-t border-[#D8D8DC] bg-white p-4"><Input aria-label="Escribe tu mensaje" value={text} onChange={(event) => setText(event.target.value)} placeholder="Escribe tu consulta..." disabled={sending}/><Button type="submit" size="icon" aria-label="Enviar mensaje" disabled={!text.trim() || sending}><Send/></Button></form></section>}<Button size="lg" className="h-12 rounded-full bg-[#8941E8] px-4 text-white hover:bg-[#7332c7]" onClick={() => setOpen((value) => !value)} aria-label={open ? "Cerrar asistente" : "Abrir asistente"}>{open ? <X/> : <MessageCircle/>}<span className="hidden sm:inline">Asistente</span></Button></div>;
}

function MarkdownMessage({ content }: { content: string }) { const normalized = content.replace(/\s+(#{1,3}\s+)/g, "\n$1").replace(/\s+-\s+(?=\*\*)/g, "\n- "); const lines = normalized.split("\n").map((line) => line.trim()).filter(Boolean); return <div className="space-y-2">{lines.map((line, index) => { const heading = line.match(/^#{1,3}\s+(.+)/); if (heading) return <h3 className="pt-2 font-semibold" key={index}>{inline(heading[1])}</h3>; const bullet = line.match(/^-\s+(.+)/); if (bullet) return <div className="flex gap-2" key={index}><span className="mt-2 size-1.5 shrink-0 rounded-full bg-current"/><p>{inline(bullet[1])}</p></div>; return <p key={index}>{inline(line)}</p>; })}</div>; }
function inline(value: string) { return value.split(/(\*\*[^*]+\*\*)/g).map((part, index) => part.startsWith("**") && part.endsWith("**") ? <strong key={index}>{part.slice(2, -2)}</strong> : <Fragment key={index}>{part}</Fragment>); }
